export const REST_API = process.env.REST_API
  ? process.env.REST_API
  : "https://prep-backend-khaki.vercel.app/api"; ;

export const countries = [
  { name: "Albania", code: "AL" },
  { name: "Åland Islands", code: "AX" },
  { name: "Algeria", code: "DZ" },
  { name: "American Samoa", code: "AS" },
  { name: "Andorra", code: "AD" },
  { name: "Angola", code: "AO" },
  { name: "Anguilla", code: "AI" },
  { name: "Antarctica", code: "AQ" },
  { name: "Antigua and Barbuda", code: "AG" },
  { name: "Argentina", code: "AR" },
  { name: "Armenia", code: "AM" },
  { name: "Aruba", code: "AW" },
  { name: "Australia", code: "AU" },
  { name: "Austria", code: "AT" },
  { name: "Azerbaijan", code: "AZ" },
  { name: "Bahamas (the)", code: "BS" },
  { name: "Bahrain", code: "BH" },
  { name: "Bangladesh", code: "BD" },
  { name: "Barbados", code: "BB" },
  { name: "Belarus", code: "BY" },
  { name: "Belgium", code: "BE" },
  { name: "Belize", code: "BZ" },
  { name: "Benin", code: "BJ" },
  { name: "Bermuda", code: "BM" },
  { name: "Bhutan", code: "BT" },
  { name: "Bolivia (Plurinational State of)", code: "BO" },
  { name: "Bonaire, Sint Eustatius and Saba", code: "BQ" },
  { name: "Bosnia and Herzegovina", code: "BA" },
  { name: "Botswana", code: "BW" },
  { name: "Bouvet Island", code: "BV" },
  { name: "Brazil", code: "BR" },
  { name: "British Indian Ocean Territory (the)", code: "IO" },
  { name: "Brunei Darussalam", code: "BN" },
  { name: "Bulgaria", code: "BG" },
  { name: "Burkina Faso", code: "BF" },
  { name: "Burundi", code: "BI" },
  { name: "Cabo Verde", code: "CV" },
  { name: "Cambodia", code: "KH" },
  { name: "Cameroon", code: "CM" },
  { name: "Canada", code: "CA" },
  { name: "Cayman Islands (the)", code: "KY" },
  { name: "Central African Republic (the)", code: "CF" },
  { name: "Chad", code: "TD" },
  { name: "Chile", code: "CL" },
  { name: "China", code: "CN" },
  { name: "Christmas Island", code: "CX" },
  { name: "Cocos (Keeling) Islands (the)", code: "CC" },
  { name: "Colombia", code: "CO" },
  { name: "Comoros (the)", code: "KM" },
  { name: "Congo (the Democratic Republic of the)", code: "CD" },
  { name: "Congo (the)", code: "CG" },
  { name: "Cook Islands (the)", code: "CK" },
  { name: "Costa Rica", code: "CR" },
  { name: "Croatia", code: "HR" },
  { name: "Cuba", code: "CU" },
  { name: "Curaçao", code: "CW" },
  { name: "Cyprus", code: "CY" },
  { name: "Czechia", code: "CZ" },
  { name: "Côte d'Ivoire", code: "CI" },
  { name: "Denmark", code: "DK" },
  { name: "Djibouti", code: "DJ" },
  { name: "Dominica", code: "DM" },
  { name: "Dominican Republic (the)", code: "DO" },
  { name: "Ecuador", code: "EC" },
  { name: "Egypt", code: "EG" },
  { name: "El Salvador", code: "SV" },
  { name: "Equatorial Guinea", code: "GQ" },
  { name: "Eritrea", code: "ER" },
  { name: "Estonia", code: "EE" },
  { name: "Eswatini", code: "SZ" },
  { name: "Ethiopia", code: "ET" },
  { name: "Falkland Islands (the) [Malvinas]", code: "FK" },
  { name: "Faroe Islands (the)", code: "FO" },
  { name: "Fiji", code: "FJ" },
  { name: "Finland", code: "FI" },
  { name: "France", code: "FR" },
  { name: "French Guiana", code: "GF" },
  { name: "French Polynesia", code: "PF" },
  { name: "French Southern Territories (the)", code: "TF" },
  { name: "Gabon", code: "GA" },
  { name: "Gambia (the)", code: "GM" },
  { name: "Georgia", code: "GE" },
  { name: "Germany", code: "DE" },
  { name: "Ghana", code: "GH" },
  { name: "Gibraltar", code: "GI" },
  { name: "Greece", code: "GR" },
  { name: "Greenland", code: "GL" },
  { name: "Grenada", code: "GD" },
  { name: "Guadeloupe", code: "GP" },
  { name: "Guam", code: "GU" },
  { name: "Guatemala", code: "GT" },
  { name: "Guernsey", code: "GG" },
  { name: "Guinea", code: "GN" },
  { name: "Guinea-Bissau", code: "GW" },
  { name: "Guyana", code: "GY" },
  { name: "Haiti", code: "HT" },
  { name: "Heard Island and McDonald Islands", code: "HM" },
  { name: "Holy See (the)", code: "VA" },
  { name: "Honduras", code: "HN" },
  { name: "Hong Kong", code: "HK" },
  { name: "Hungary", code: "HU" },
  { name: "Iceland", code: "IS" },
  { name: "India", code: "IN" },
  { name: "Indonesia", code: "ID" },
  { name: "Iran (Islamic Republic of)", code: "IR" },
  { name: "Iraq", code: "IQ" },
  { name: "Ireland", code: "IE" },
  { name: "Isle of Man", code: "IM" },
  { name: "Israel", code: "IL" },
  { name: "Italy", code: "IT" },
  { name: "Jamaica", code: "JM" },
  { name: "Japan", code: "JP" },
  { name: "Jersey", code: "JE" },
  { name: "Jordan", code: "JO" },
  { name: "Kazakhstan", code: "KZ" },
  { name: "Kenya", code: "KE" },
  { name: "Kiribati", code: "KI" },
  { name: "Korea (the Democratic People's Republic of)", code: "KP" },
  { name: "Korea (the Republic of)", code: "KR" },
  { name: "Kuwait", code: "KW" },
  { name: "Kyrgyzstan", code: "KG" },
  { name: "Lao People's Democratic Republic (the)", code: "LA" },
  { name: "Latvia", code: "LV" },
  { name: "Lebanon", code: "LB" },
  { name: "Lesotho", code: "LS" },
  { name: "Liberia", code: "LR" },
  { name: "Libya", code: "LY" },
  { name: "Liechtenstein", code: "LI" },
  { name: "Lithuania", code: "LT" },
  { name: "Luxembourg", code: "LU" },
  { name: "Macao", code: "MO" },
  { name: "Madagascar", code: "MG" },
  { name: "Malawi", code: "MW" },
  { name: "Malaysia", code: "MY" },
  { name: "Maldives", code: "MV" },
  { name: "Mali", code: "ML" },
  { name: "Malta", code: "MT" },
  { name: "Marshall Islands (the)", code: "MH" },
  { name: "Martinique", code: "MQ" },
  { name: "Mauritania", code: "MR" },
  { name: "Mauritius", code: "MU" },
  { name: "Mayotte", code: "YT" },
  { name: "Mexico", code: "MX" },
  { name: "Micronesia (Federated States of)", code: "FM" },
  { name: "Moldova (the Republic of)", code: "MD" },
  { name: "Monaco", code: "MC" },
  { name: "Mongolia", code: "MN" },
  { name: "Montenegro", code: "ME" },
  { name: "Montserrat", code: "MS" },
  { name: "Morocco", code: "MA" },
  { name: "Mozambique", code: "MZ" },
  { name: "Myanmar", code: "MM" },
  { name: "Namibia", code: "NA" },
  { name: "Nauru", code: "NR" },
  { name: "Nepal", code: "NP" },
  { name: "Netherlands (the)", code: "NL" },
  { name: "New Caledonia", code: "NC" },
  { name: "New Zealand", code: "NZ" },
  { name: "Nicaragua", code: "NI" },
  { name: "Niger (the)", code: "NE" },
  { name: "Nigeria", code: "NG" },
  { name: "Niue", code: "NU" },
  { name: "Norfolk Island", code: "NF" },
  { name: "Northern Mariana Islands (the)", code: "MP" },
  { name: "Norway", code: "NO" },
  { name: "Oman", code: "OM" },
  { name: "Pakistan", code: "PK" },
  { name: "Palau", code: "PW" },
  { name: "Palestine, State of", code: "PS" },
  { name: "Panama", code: "PA" },
  { name: "Papua New Guinea", code: "PG" },
  { name: "Paraguay", code: "PY" },
  { name: "Peru", code: "PE" },
  { name: "Philippines (the)", code: "PH" },
  { name: "Pitcairn", code: "PN" },
  { name: "Poland", code: "PL" },
  { name: "Portugal", code: "PT" },
  { name: "Puerto Rico", code: "PR" },
  { name: "Qatar", code: "QA" },
  { name: "Republic of North Macedonia", code: "MK" },
  { name: "Romania", code: "RO" },
  { name: "Russian Federation (the)", code: "RU" },
  { name: "Rwanda", code: "RW" },
  { name: "Réunion", code: "RE" },
  { name: "Saint Barthélemy", code: "BL" },
  { name: "Saint Helena, Ascension and Tristan da Cunha", code: "SH" },
  { name: "Saint Kitts and Nevis", code: "KN" },
  { name: "Saint Lucia", code: "LC" },
  { name: "Saint Martin (French part)", code: "MF" },
  { name: "Saint Pierre and Miquelon", code: "PM" },
  { name: "Saint Vincent and the Grenadines", code: "VC" },
  { name: "Samoa", code: "WS" },
  { name: "San Marino", code: "SM" },
  { name: "Sao Tome and Principe", code: "ST" },
  { name: "Saudi Arabia", code: "SA" },
  { name: "Senegal", code: "SN" },
  { name: "Serbia", code: "RS" },
  { name: "Seychelles", code: "SC" },
  { name: "Sierra Leone", code: "SL" },
  { name: "Singapore", code: "SG" },
  { name: "Sint Maarten (Dutch part)", code: "SX" },
  { name: "Slovakia", code: "SK" },
  { name: "Slovenia", code: "SI" },
  { name: "Solomon Islands", code: "SB" },
  { name: "Somalia", code: "SO" },
  { name: "South Africa", code: "ZA" },
  { name: "South Georgia and the South Sandwich Islands", code: "GS" },
  { name: "South Sudan", code: "SS" },
  { name: "Spain", code: "ES" },
  { name: "Sri Lanka", code: "LK" },
  { name: "Sudan (the)", code: "SD" },
  { name: "Suriname", code: "SR" },
  { name: "Svalbard and Jan Mayen", code: "SJ" },
  { name: "Sweden", code: "SE" },
  { name: "Switzerland", code: "CH" },
  { name: "Syrian Arab Republic", code: "SY" },
  { name: "Taiwan (Province of China)", code: "TW" },
  { name: "Tajikistan", code: "TJ" },
  { name: "Tanzania, United Republic of", code: "TZ" },
  { name: "Thailand", code: "TH" },
  { name: "Timor-Leste", code: "TL" },
  { name: "Togo", code: "TG" },
  { name: "Tokelau", code: "TK" },
  { name: "Tonga", code: "TO" },
  { name: "Trinidad and Tobago", code: "TT" },
  { name: "Tunisia", code: "TN" },
  { name: "Turkey", code: "TR" },
  { name: "Turkmenistan", code: "TM" },
  { name: "Turks and Caicos Islands (the)", code: "TC" },
  { name: "Tuvalu", code: "TV" },
  { name: "Uganda", code: "UG" },
  { name: "Ukraine", code: "UA" },
  { name: "United Arab Emirates (the)", code: "AE" },
  {
    name: "United Kingdom of Great Britain and Northern Ireland (the)",
    code: "GB",
  },
  { name: "United States Minor Outlying Islands (the)", code: "UM" },
  { name: "United States of America (the)", code: "US" },
  { name: "Uruguay", code: "UY" },
  { name: "Uzbekistan", code: "UZ" },
  { name: "Vanuatu", code: "VU" },
  { name: "Venezuela (Bolivarian Republic of)", code: "VE" },
  { name: "Viet Nam", code: "VN" },
  { name: "Virgin Islands (British)", code: "VG" },
  { name: "Virgin Islands (U.S.)", code: "VI" },
  { name: "Wallis and Futuna", code: "WF" },
  { name: "Western Sahara", code: "EH" },
  { name: "Yemen", code: "YE" },
  { name: "Zambia", code: "ZM" },
  { name: "Zimbabwe", code: "ZW" },
];

export const schools = [
  {
    name: "University of Lagos",
    type: "Federal",
    location: "Lagos",
  },
  {
    name: "University of Ibadan",
    type: "Federal",
    location: "Oyo",
  },
  {
    name: "Ahmadu Bello University",
    type: "Federal",
    location: "Kaduna",
  },
  {
    name: "University of Nigeria, Nsukka",
    type: "Federal",
    location: "Enugu",
  },
  {
    name: "Obafemi Awolowo University",
    type: "Federal",
    location: "Osun",
  },
  {
    name: "University of Benin",
    type: "Federal",
    location: "Edo",
  },
  {
    name: "Abubakar Tafawa Balewa University",
    type: "Federal",
    location: "Bauchi",
  },
  {
    name: "Bayero University Kano",
    type: "Federal",
    location: "Kano",
  },
  {
    name: "University of Port Harcourt",
    type: "Federal",
    location: "Rivers",
  },
  {
    name: "Federal University of Technology, Minna",
    type: "Federal",
    location: "Niger",
  },
  {
    name: "Ambrose Alli University",
    type: "State",
    location: "Ekpoma",
  },
  {
    name: "Abia State University",
    type: "State",
    location: "Uturu",
  },
  {
    name: "Covenant University",
    type: "Private",
    location: "Ota",
  },
  {
    name: "Pan-Atlantic University",
    type: "Private",
    location: "Lagos",
  },
];

export const allCourses = [
  "Computer Science & IT",
  "Engineering (Mechanical, Civil, Electrical, Software, Aerospace)",
  "Health Sciences (Medicine, Nursing, Psychology)",
  "Business & Management (Finance, Accounting, Marketing, Analytics)",
  "Natural Sciences (Biology, Chemistry, Physics, Environmental Science)",
  "Social Sciences (Sociology, Economics, Political Science, Criminology)",
  "Creative Arts & Design (Fine Arts, Graphic Design, Media Studies, Music)",
  "Humanities (History, Literature, Philosophy, Languages)",
  "Education & Training",
  "Law",
  "Architecture",
  "Agriculture & Forestry",
  "Interdisciplinary Fields (e.g., Bioinformatics, Data Science)",
];


export const countryCode = [
  {
    name: "Afghanistan",
    code: "AF",
    phoneCode: "+93",
    flagEmoji: "🇦🇫",
  },
  {
    name: "Aland Islands",
    code: "AX",
    phoneCode: "+358",
    flagEmoji: "🇦🇽",
  },
  {
    name: "Albania",
    code: "AL",
    phoneCode: "+355",
    flagEmoji: "🇦🇱",
  },
  {
    name: "Algeria",
    code: "DZ",
    phoneCode: "+213",
    flagEmoji: "🇩🇿",
  },
  {
    name: "AmericanSamoa",
    code: "AS",
    phoneCode: "+1684",
    flagEmoji: "🇦🇸",
  },
  {
    name: "Andorra",
    code: "AD",
    phoneCode: "+376",
    flagEmoji: "🇦🇩",
  },
  {
    name: "Angola",
    code: "AO",
    phoneCode: "+244",
    flagEmoji: "🇦🇴",
  },
  {
    name: "Anguilla",
    code: "AI",
    phoneCode: "+1264",
    flagEmoji: "🇦🇮",
  },
  {
    name: "Antarctica",
    code: "AQ",
    phoneCode: "+672",
    flagEmoji: "🇦🇶",
  },
  {
    name: "Antigua and Barbuda",
    code: "AG",
    phoneCode: "+1268",
    flagEmoji: "🇦🇬",
  },
  {
    name: "Argentina",
    code: "AR",
    phoneCode: "+54",
    flagEmoji: "🇦🇷",
  },
  {
    name: "Armenia",
    code: "AM",
    phoneCode: "+374",
    flagEmoji: "🇦🇲",
  },
  {
    name: "Aruba",
    code: "AW",
    phoneCode: "+297",
    flagEmoji: "🇦🇼",
  },
  {
    name: "Australia",
    code: "AU",
    phoneCode: "+61",
    flagEmoji: "🇦🇺",
  },
  {
    name: "Austria",
    code: "AT",
    phoneCode: "+43",
    flagEmoji: "🇦🇹",
  },
  {
    name: "Azerbaijan",
    code: "AZ",
    phoneCode: "+994",
    flagEmoji: "🇦🇿",
  },
  {
    name: "Bahamas",
    code: "BS",
    phoneCode: "+1242",
    flagEmoji: "🇧🇸",
  },
  {
    name: "Bahrain",
    code: "BH",
    phoneCode: "+973",
    flagEmoji: "🇧🇭",
  },
  {
    name: "Bangladesh",
    code: "BD",
    phoneCode: "+880",
    flagEmoji: "🇧🇩",
  },
  {
    name: "Barbados",
    code: "BB",
    phoneCode: "+1246",
    flagEmoji: "🇧🇧",
  },
  {
    name: "Belarus",
    code: "BY",
    phoneCode: "+375",
    flagEmoji: "🇧🇾",
  },
  {
    name: "Belgium",
    code: "BE",
    phoneCode: "+32",
    flagEmoji: "🇧🇪",
  },
  {
    name: "Belize",
    code: "BZ",
    phoneCode: "+501",
    flagEmoji: "🇧🇿",
  },
  {
    name: "Benin",
    code: "BJ",
    phoneCode: "+229",
    flagEmoji: "🇧🇯",
  },
  {
    name: "Bermuda",
    code: "BM",
    phoneCode: "+1441",
    flagEmoji: "🇧🇲",
  },
  {
    name: "Bhutan",
    code: "BT",
    phoneCode: "+975",
    flagEmoji: "🇧🇹",
  },
  {
    name: "Bolivia, Plurinational State of",
    code: "BO",
    phoneCode: "+591",
    flagEmoji: "🇧🇴",
  },
  {
    name: "Bosnia and Herzegovina",
    code: "BA",
    phoneCode: "+387",
    flagEmoji: "🇧🇦",
  },
  {
    name: "Botswana",
    code: "BW",
    phoneCode: "+267",
    flagEmoji: "🇧🇼",
  },
  {
    name: "Brazil",
    code: "BR",
    phoneCode: "+55",
    flagEmoji: "🇧🇷",
  },
  {
    name: "British Indian Ocean Territory",
    code: "IO",
    phoneCode: "+246",
    flagEmoji: "🇮🇴",
  },
  {
    name: "Brunei Darussalam",
    code: "BN",
    phoneCode: "+673",
    flagEmoji: "🇧🇳",
  },
  {
    name: "Bulgaria",
    code: "BG",
    phoneCode: "+359",
    flagEmoji: "🇧🇬",
  },
  {
    name: "Burkina Faso",
    code: "BF",
    phoneCode: "+226",
    flagEmoji: "🇧🇫",
  },
  {
    name: "Burundi",
    code: "BI",
    phoneCode: "+257",
    flagEmoji: "🇧🇮",
  },
  {
    name: "Cambodia",
    code: "KH",
    phoneCode: "+855",
    flagEmoji: "🇰🇭",
  },
  {
    name: "Cameroon",
    code: "CM",
    phoneCode: "+237",
    flagEmoji: "🇨🇲",
  },
  {
    name: "Canada",
    code: "CA",
    phoneCode: "+1",
    flagEmoji: "🇨🇦",
  },
  {
    name: "Cape Verde",
    code: "CV",
    phoneCode: "+238",
    flagEmoji: "🇨🇻",
  },
  {
    name: "Cayman Islands",
    code: "KY",
    phoneCode: "+345",
    flagEmoji: "🇰🇾",
  },
  {
    name: "Central African Republic",
    code: "CF",
    phoneCode: "+236",
    flagEmoji: "🇨🇫",
  },
  {
    name: "Chad",
    code: "TD",
    phoneCode: "+235",
    flagEmoji: "🇹🇩",
  },
  {
    name: "Chile",
    code: "CL",
    phoneCode: "+56",
    flagEmoji: "🇨🇱",
  },
  {
    name: "China",
    code: "CN",
    phoneCode: "+86",
    flagEmoji: "🇨🇳",
  },
  {
    name: "Christmas Island",
    code: "CX",
    phoneCode: "+61",
    flagEmoji: "🇨🇽",
  },
  {
    name: "Cocos (Keeling) Islands",
    code: "CC",
    phoneCode: "+61",
    flagEmoji: "🇨🇨",
  },
  {
    name: "Colombia",
    code: "CO",
    phoneCode: "+57",
    flagEmoji: "🇨🇴",
  },
  {
    name: "Comoros",
    code: "KM",
    phoneCode: "+269",
    flagEmoji: "🇰🇲",
  },
  {
    name: "Congo",
    code: "CG",
    phoneCode: "+242",
    flagEmoji: "🇨🇬",
  },
  {
    name: "Congo, The Democratic Republic of the Congo",
    code: "CD",
    phoneCode: "+243",
    flagEmoji: "🇨🇩",
  },
  {
    name: "Cook Islands",
    code: "CK",
    phoneCode: "+682",
    flagEmoji: "🇨🇰",
  },
  {
    name: "Costa Rica",
    code: "CR",
    phoneCode: "+506",
    flagEmoji: "🇨🇷",
  },
  {
    name: "Cote d'Ivoire",
    code: "CI",
    phoneCode: "+225",
    flagEmoji: "🇨🇮",
  },
  {
    name: "Croatia",
    code: "HR",
    phoneCode: "+385",
    flagEmoji: "🇭🇷",
  },
  {
    name: "Cuba",
    code: "CU",
    phoneCode: "+53",
    flagEmoji: "🇨🇺",
  },
  {
    name: "Cyprus",
    code: "CY",
    phoneCode: "+357",
    flagEmoji: "🇨🇾",
  },
  {
    name: "Czech Republic",
    code: "CZ",
    phoneCode: "+420",
    flagEmoji: "🇨🇿",
  },
  {
    name: "Denmark",
    code: "DK",
    phoneCode: "+45",
    flagEmoji: "🇩🇰",
  },
  {
    name: "Djibouti",
    code: "DJ",
    phoneCode: "+253",
    flagEmoji: "🇩🇯",
  },
  {
    name: "Dominica",
    code: "DM",
    phoneCode: "+1767",
    flagEmoji: "🇩🇲",
  },
  {
    name: "Dominican Republic",
    code: "DO",
    phoneCode: "+1849",
    flagEmoji: "🇩🇴",
  },
  {
    name: "Ecuador",
    code: "EC",
    phoneCode: "+593",
    flagEmoji: "🇪🇨",
  },
  {
    name: "Egypt",
    code: "EG",
    phoneCode: "+20",
    flagEmoji: "🇪🇬",
  },
  {
    name: "El Salvador",
    code: "SV",
    phoneCode: "+503",
    flagEmoji: "🇸🇻",
  },
  {
    name: "Equatorial Guinea",
    code: "GQ",
    phoneCode: "+240",
    flagEmoji: "🇬🇶",
  },
  {
    name: "Eritrea",
    code: "ER",
    phoneCode: "+291",
    flagEmoji: "🇪🇷",
  },
  {
    name: "Estonia",
    code: "EE",
    phoneCode: "+372",
    flagEmoji: "🇪🇪",
  },
  {
    name: "Ethiopia",
    code: "ET",
    phoneCode: "+251",
    flagEmoji: "🇪🇹",
  },
  {
    name: "Falkland Islands (Malvinas)",
    code: "FK",
    phoneCode: "+500",
    flagEmoji: "🇫🇰",
  },
  {
    name: "Faroe Islands",
    code: "FO",
    phoneCode: "+298",
    flagEmoji: "🇫🇴",
  },
  {
    name: "Fiji",
    code: "FJ",
    phoneCode: "+679",
    flagEmoji: "🇫🇯",
  },
  {
    name: "Finland",
    code: "FI",
    phoneCode: "+358",
    flagEmoji: "🇫🇮",
  },
  {
    name: "France",
    code: "FR",
    phoneCode: "+33",
    flagEmoji: "🇫🇷",
  },
  {
    name: "French Guiana",
    code: "GF",
    phoneCode: "+594",
    flagEmoji: "🇬🇫",
  },
  {
    name: "French Polynesia",
    code: "PF",
    phoneCode: "+689",
    flagEmoji: "🇵🇫",
  },
  {
    name: "Gabon",
    code: "GA",
    phoneCode: "+241",
    flagEmoji: "🇬🇦",
  },
  {
    name: "Gambia",
    code: "GM",
    phoneCode: "+220",
    flagEmoji: "🇬🇲",
  },
  {
    name: "Georgia",
    code: "GE",
    phoneCode: "+995",
    flagEmoji: "🇬🇪",
  },
  {
    name: "Germany",
    code: "DE",
    phoneCode: "+49",
    flagEmoji: "🇩🇪",
  },
  {
    name: "Ghana",
    code: "GH",
    phoneCode: "+233",
    flagEmoji: "🇬🇭",
  },
  {
    name: "Gibraltar",
    code: "GI",
    phoneCode: "+350",
    flagEmoji: "🇬🇮",
  },
  {
    name: "Greece",
    code: "GR",
    phoneCode: "+30",
    flagEmoji: "🇬🇷",
  },
  {
    name: "Greenland",
    code: "GL",
    phoneCode: "+299",
    flagEmoji: "🇬🇱",
  },
  {
    name: "Grenada",
    code: "GD",
    phoneCode: "+1473",
    flagEmoji: "🇬🇩",
  },
  {
    name: "Guadeloupe",
    code: "GP",
    phoneCode: "+590",
    flagEmoji: "🇬🇵",
  },
  {
    name: "Guam",
    code: "GU",
    phoneCode: "+1671",
    flagEmoji: "🇬🇺",
  },
  {
    name: "Guatemala",
    code: "GT",
    phoneCode: "+502",
    flagEmoji: "🇬🇹",
  },
  {
    name: "Guernsey",
    code: "GG",
    phoneCode: "+44",
    flagEmoji: "🇬🇬",
  },
  {
    name: "Guinea",
    code: "GN",
    phoneCode: "+224",
    flagEmoji: "🇬🇳",
  },
  {
    name: "Guinea-Bissau",
    code: "GW",
    phoneCode: "+245",
    flagEmoji: "🇬🇼",
  },
  {
    name: "Guyana",
    code: "GY",
    phoneCode: "+595",
    flagEmoji: "🇬🇾",
  },
  {
    name: "Haiti",
    code: "HT",
    phoneCode: "+509",
    flagEmoji: "🇭🇹",
  },
  {
    name: "Holy See (Vatican City State)",
    code: "VA",
    phoneCode: "+379",
    flagEmoji: "🇻🇦",
  },
  {
    name: "Honduras",
    code: "HN",
    phoneCode: "+504",
    flagEmoji: "🇭🇳",
  },
  {
    name: "Hong Kong",
    code: "HK",
    phoneCode: "+852",
    flagEmoji: "🇭🇰",
  },
  {
    name: "Hungary",
    code: "HU",
    phoneCode: "+36",
    flagEmoji: "🇭🇺",
  },
  {
    name: "Iceland",
    code: "IS",
    phoneCode: "+354",
    flagEmoji: "🇮🇸",
  },
  {
    name: "India",
    code: "IN",
    phoneCode: "+91",
    flagEmoji: "🇮🇳",
  },
  {
    name: "Indonesia",
    code: "ID",
    phoneCode: "+62",
    flagEmoji: "🇮🇩",
  },
  {
    name: "Iran, Islamic Republic of Persian Gulf",
    code: "IR",
    phoneCode: "+98",
    flagEmoji: "🇮🇷",
  },
  {
    name: "Iraq",
    code: "IQ",
    phoneCode: "+964",
    flagEmoji: "🇮🇷",
  },
  {
    name: "Ireland",
    code: "IE",
    phoneCode: "+353",
    flagEmoji: "🇮🇪",
  },
  {
    name: "Isle of Man",
    code: "IM",
    phoneCode: "+44",
    flagEmoji: "🇮🇲",
  },
  {
    name: "Israel",
    code: "IL",
    phoneCode: "+972",
    flagEmoji: "🇮🇱",
  },
  {
    name: "Italy",
    code: "IT",
    phoneCode: "+39",
    flagEmoji: "🇮🇹",
  },
  {
    name: "Jamaica",
    code: "JM",
    phoneCode: "+1876",
    flagEmoji: "🇯🇲",
  },
  {
    name: "Japan",
    code: "JP",
    phoneCode: "+81",
    flagEmoji: "🇯🇵",
  },
  {
    name: "Jersey",
    code: "JE",
    phoneCode: "+44",
    flagEmoji: "🇯🇪",
  },
  {
    name: "Jordan",
    code: "JO",
    phoneCode: "+962",
    flagEmoji: "🇯🇴",
  },
  {
    name: "Kazakhstan",
    code: "KZ",
    phoneCode: "+77",
    flagEmoji: "🇰🇿",
  },
  {
    name: "Kenya",
    code: "KE",
    phoneCode: "+254",
    flagEmoji: "🇰🇪",
  },
  {
    name: "Kiribati",
    code: "KI",
    phoneCode: "+686",
    flagEmoji: "🇰🇮",
  },
  {
    name: "Korea, Democratic People's Republic of Korea",
    code: "KP",
    phoneCode: "+850",
    flagEmoji: "🇰🇵",
  },
  {
    name: "Korea, Republic of South Korea",
    code: "KR",
    phoneCode: "+82",
    flagEmoji: "🇰🇷",
  },
  {
    name: "Kuwait",
    code: "KW",
    phoneCode: "+965",
    flagEmoji: "🇰🇼",
  },
  {
    name: "Kyrgyzstan",
    code: "KG",
    phoneCode: "+996",
    flagEmoji: "🇰🇬",
  },
  {
    name: "Laos",
    code: "LA",
    phoneCode: "+856",
    flagEmoji: "🇱🇦",
  },
  {
    name: "Latvia",
    code: "LV",
    phoneCode: "+371",
    flagEmoji: "🇱🇻",
  },
  {
    name: "Lebanon",
    code: "LB",
    phoneCode: "+961",
    flagEmoji: "🇱🇧",
  },
  {
    name: "Lesotho",
    code: "LS",
    phoneCode: "+266",
    flagEmoji: "🇱🇸",
  },
  {
    name: "Liberia",
    code: "LR",
    phoneCode: "+231",
    flagEmoji: "🇱🇷",
  },
  {
    name: "Libyan Arab Jamahiriya",
    code: "LY",
    phoneCode: "+218",
    flagEmoji: "🇱🇾",
  },
  {
    name: "Liechtenstein",
    code: "LI",
    phoneCode: "+423",
    flagEmoji: "🇱🇮",
  },
  {
    name: "Lithuania",
    code: "LT",
    phoneCode: "+370",
    flagEmoji: "🇱🇹",
  },
  {
    name: "Luxembourg",
    code: "LU",
    phoneCode: "+352",
    flagEmoji: "🇱🇺",
  },
  {
    name: "Macao",
    code: "MO",
    phoneCode: "+853",
    flagEmoji: "🇲🇴",
  },
  {
    name: "Macedonia",
    code: "MK",
    phoneCode: "+389",
    flagEmoji: "🇲🇰",
  },
  {
    name: "Madagascar",
    code: "MG",
    phoneCode: "+261",
    flagEmoji: "🇲🇬",
  },
  {
    name: "Malawi",
    code: "MW",
    phoneCode: "+265",
    flagEmoji: "🇲🇼",
  },
  {
    name: "Malaysia",
    code: "MY",
    phoneCode: "+60",
    flagEmoji: "🇲🇾",
  },
  {
    name: "Maldives",
    code: "MV",
    phoneCode: "+960",
    flagEmoji: "🇲🇻",
  },
  {
    name: "Mali",
    code: "ML",
    phoneCode: "+223",
    flagEmoji: "🇲🇱",
  },
  {
    name: "Malta",
    code: "MT",
    phoneCode: "+356",
    flagEmoji: "🇲🇹",
  },
  {
    name: "Marshall Islands",
    code: "MH",
    phoneCode: "+692",
    flagEmoji: "🇲🇭",
  },
  {
    name: "Martinique",
    code: "MQ",
    phoneCode: "+596",
    flagEmoji: "🇲🇶",
  },
  {
    name: "Mauritania",
    code: "MR",
    phoneCode: "+222",
    flagEmoji: "🇲🇷",
  },
  {
    name: "Mauritius",
    code: "MU",
    phoneCode: "+230",
    flagEmoji: "🇲🇺",
  },
  {
    name: "Mayotte",
    code: "YT",
    phoneCode: "+262",
    flagEmoji: "🇾🇹",
  },
  {
    name: "Mexico",
    code: "MX",
    phoneCode: "+52",
    flagEmoji: "🇲🇽",
  },
  {
    name: "Micronesia, Federated States of Micronesia",
    code: "FM",
    phoneCode: "+691",
    flagEmoji: "🇫🇲",
  },
  {
    name: "Moldova",
    code: "MD",
    phoneCode: "+373",
    flagEmoji: "🇲🇩",
  },
  {
    name: "Monaco",
    code: "MC",
    phoneCode: "+377",
    flagEmoji: "🇲🇨",
  },
  {
    name: "Mongolia",
    code: "MN",
    phoneCode: "+976",
    flagEmoji: "🇲🇳",
  },
  {
    name: "Montenegro",
    code: "ME",
    phoneCode: "+382",
    flagEmoji: "🇲🇪",
  },
  {
    name: "Montserrat",
    code: "MS",
    phoneCode: "+1664",
    flagEmoji: "🇲🇸",
  },
  {
    name: "Morocco",
    code: "MA",
    phoneCode: "+212",
    flagEmoji: "🇲🇦",
  },
  {
    name: "Mozambique",
    code: "MZ",
    phoneCode: "+258",
    flagEmoji: "🇲🇿",
  },
  {
    name: "Myanmar",
    code: "MM",
    phoneCode: "+95",
    flagEmoji: "🇲🇲",
  },
  {
    name: "Namibia",
    code: "NA",
    phoneCode: "+264",
    flagEmoji: "🇳🇦",
  },
  {
    name: "Nauru",
    code: "NR",
    phoneCode: "+674",
    flagEmoji: "🇳🇷",
  },
  {
    name: "Nepal",
    code: "NP",
    phoneCode: "+977",
    flagEmoji: "🇳🇵",
  },
  {
    name: "Netherlands",
    code: "NL",
    phoneCode: "+31",
    flagEmoji: "🇳🇱",
  },
  {
    name: "Netherlands Antilles",
    code: "AN",
    phoneCode: "+599",
    flagEmoji: "🇧🇶",
  },
  {
    name: "New Caledonia",
    code: "NC",
    phoneCode: "+687",
    flagEmoji: "🇳🇨",
  },
  {
    name: "New Zealand",
    code: "NZ",
    phoneCode: "+64",
    flagEmoji: "🇳🇿",
  },
  {
    name: "Nicaragua",
    code: "NI",
    phoneCode: "+505",
    flagEmoji: "🇳🇮",
  },
  {
    name: "Niger",
    code: "NE",
    phoneCode: "+227",
    flagEmoji: "🇳🇪",
  },
  {
    name: "Nigeria",
    code: "NG",
    phoneCode: "+234",
    flagEmoji: "🇳🇬",
  },
  {
    name: "Niue",
    code: "NU",
    phoneCode: "+683",
    flagEmoji: "🇳🇺",
  },
  {
    name: "Norfolk Island",
    code: "NF",
    phoneCode: "+672",
    flagEmoji: "🇳🇫",
  },
  {
    name: "Northern Mariana Islands",
    code: "MP",
    phoneCode: "+1670",
    flagEmoji: "🇲🇵",
  },
  {
    name: "Norway",
    code: "NO",
    phoneCode: "+47",
    flagEmoji: "🇳🇴",
  },
  {
    name: "Oman",
    code: "OM",
    phoneCode: "+968",
    flagEmoji: "🇴🇲",
  },
  {
    name: "Pakistan",
    code: "PK",
    phoneCode: "+92",
    flagEmoji: "🇵🇰",
  },
  {
    name: "Palau",
    code: "PW",
    phoneCode: "+680",
    flagEmoji: "🇵🇼",
  },
  {
    name: "Palestinian Territory, Occupied",
    code: "PS",
    phoneCode: "+970",
    flagEmoji: "🇵🇸",
  },
  {
    name: "Panama",
    code: "PA",
    phoneCode: "+507",
    flagEmoji: "🇵🇦",
  },
  {
    name: "Papua New Guinea",
    code: "PG",
    phoneCode: "+675",
    flagEmoji: "🇵🇬",
  },
  {
    name: "Paraguay",
    code: "PY",
    phoneCode: "+595",
    flagEmoji: "🇵🇾",
  },
  {
    name: "Peru",
    code: "PE",
    phoneCode: "+51",
    flagEmoji: "🇵🇪",
  },
  {
    name: "Philippines",
    code: "PH",
    phoneCode: "+63",
    flagEmoji: "🇵🇭",
  },
  {
    name: "Pitcairn",
    code: "PN",
    phoneCode: "+872",
    flagEmoji: "🇵🇳",
  },
  {
    name: "Poland",
    code: "PL",
    phoneCode: "+48",
    flagEmoji: "🇵🇱",
  },
  {
    name: "Portugal",
    code: "PT",
    phoneCode: "+351",
    flagEmoji: "🇵🇹",
  },
  {
    name: "Puerto Rico",
    code: "PR",
    phoneCode: "+1939",
    flagEmoji: "🇵🇷",
  },
  {
    name: "Qatar",
    code: "QA",
    phoneCode: "+974",
    flagEmoji: "🇶🇦",
  },
  {
    name: "Reunion",
    code: "RE",
    phoneCode: "+262",
    flagEmoji: "🇷🇪",
  },
  {
    name: "Romania",
    code: "RO",
    phoneCode: "+40",
    flagEmoji: "🇷🇴",
  },
  {
    name: "Russia",
    code: "RU",
    phoneCode: "+7",
    flagEmoji: "🇷🇺",
  },
  {
    name: "Rwanda",
    code: "RW",
    phoneCode: "+250",
    flagEmoji: "🇷🇼",
  },
  {
    name: "Saint Barthelemy",
    code: "BL",
    phoneCode: "+590",
    flagEmoji: "🇧🇱",
  },
  {
    name: "Saint Helena, Ascension and Tristan Da Cunha",
    code: "SH",
    phoneCode: "+290",
    flagEmoji: "🇸🇭",
  },
  {
    name: "Saint Kitts and Nevis",
    code: "KN",
    phoneCode: "+1869",
    flagEmoji: "🇰🇳",
  },
  {
    name: "Saint Lucia",
    code: "LC",
    phoneCode: "+1758",
    flagEmoji: "🇱🇨",
  },
  {
    name: "Saint Martin",
    code: "MF",
    phoneCode: "+590",
    flagEmoji: "🇲🇫",
  },
  {
    name: "Saint Pierre and Miquelon",
    code: "PM",
    phoneCode: "+508",
    flagEmoji: "🇵🇲",
  },
  {
    name: "Saint Vincent and the Grenadines",
    code: "VC",
    phoneCode: "+1784",
    flagEmoji: "🇻🇨",
  },
  {
    name: "Samoa",
    code: "WS",
    phoneCode: "+685",
    flagEmoji: "🇼🇸",
  },
  {
    name: "San Marino",
    code: "SM",
    phoneCode: "+378",
    flagEmoji: "🇸🇲",
  },
  {
    name: "Sao Tome and Principe",
    code: "ST",
    phoneCode: "+239",
    flagEmoji: "🇸🇹",
  },
  {
    name: "Saudi Arabia",
    code: "SA",
    phoneCode: "+966",
    flagEmoji: "🇸🇦",
  },
  {
    name: "Senegal",
    code: "SN",
    phoneCode: "+221",
    flagEmoji: "🇸🇳",
  },
  {
    name: "Serbia",
    code: "RS",
    phoneCode: "+381",
    flagEmoji: "🇷🇸",
  },
  {
    name: "Seychelles",
    code: "SC",
    phoneCode: "+248",
    flagEmoji: "🇸🇨",
  },
  {
    name: "Sierra Leone",
    code: "SL",
    phoneCode: "+232",
    flagEmoji: "🇸🇱",
  },
  {
    name: "Singapore",
    code: "SG",
    phoneCode: "+65",
    flagEmoji: "🇸🇬",
  },
  {
    name: "Slovakia",
    code: "SK",
    phoneCode: "+421",
    flagEmoji: "🇸🇰",
  },
  {
    name: "Slovenia",
    code: "SI",
    phoneCode: "+386",
    flagEmoji: "🇸🇮",
  },
  {
    name: "Solomon Islands",
    code: "SB",
    phoneCode: "+677",
    flagEmoji: "🇸🇧",
  },
  {
    name: "Somalia",
    code: "SO",
    phoneCode: "+252",
    flagEmoji: "🇸🇴",
  },
  {
    name: "South Africa",
    code: "ZA",
    phoneCode: "+27",
    flagEmoji: "🇿🇦",
  },
  {
    name: "South Georgia and the South Sandwich Islands",
    code: "GS",
    phoneCode: "+500",
    flagEmoji: "🇬🇸",
  },
  {
    name: "South Sudan",
    code: "SS",
    phoneCode: "+211",
    flagEmoji: "🇸🇸",
  },
  {
    name: "Spain",
    code: "ES",
    phoneCode: "+34",
    flagEmoji: "🇪🇸",
  },
  {
    name: "Sri Lanka",
    code: "LK",
    phoneCode: "+94",
    flagEmoji: "🇱🇰",
  },
  {
    name: "Sudan",
    code: "SD",
    phoneCode: "+249",
    flagEmoji: "🇸🇩",
  },
  {
    name: "Suriname",
    code: "SR",
    phoneCode: "+597",
    flagEmoji: "🇸🇷",
  },
  {
    name: "Svalbard and Jan Mayen",
    code: "SJ",
    phoneCode: "+47",
    flagEmoji: "🇸🇯",
  },
  {
    name: "Swaziland",
    code: "SZ",
    phoneCode: "+268",
    flagEmoji: "🇸🇿",
  },
  {
    name: "Sweden",
    code: "SE",
    phoneCode: "+46",
    flagEmoji: "🇸🇪",
  },
  {
    name: "Switzerland",
    code: "CH",
    phoneCode: "+41",
    flagEmoji: "🇨🇭",
  },
  {
    name: "Syrian Arab Republic",
    code: "SY",
    phoneCode: "+963",
    flagEmoji: "🇸🇾",
  },
  {
    name: "Taiwan",
    code: "TW",
    phoneCode: "+886",
    flagEmoji: "🇹🇼",
  },
  {
    name: "Tajikistan",
    code: "TJ",
    phoneCode: "+992",
    flagEmoji: "🇹🇯",
  },
  {
    name: "Tanzania, United Republic of Tanzania",
    code: "TZ",
    phoneCode: "+255",
    flagEmoji: "🇹🇿",
  },
  {
    name: "Thailand",
    code: "TH",
    phoneCode: "+66",
    flagEmoji: "🇹🇭",
  },
  {
    name: "Timor-Leste",
    code: "TL",
    phoneCode: "+670",
    flagEmoji: "🇹🇱",
  },
  {
    name: "Togo",
    code: "TG",
    phoneCode: "+228",
    flagEmoji: "🇹🇬",
  },
  {
    name: "Tokelau",
    code: "TK",
    phoneCode: "+690",
    flagEmoji: "🇹🇰",
  },
  {
    name: "Tonga",
    code: "TO",
    phoneCode: "+676",
    flagEmoji: "🇹🇴",
  },
  {
    name: "Trinidad and Tobago",
    code: "TT",
    phoneCode: "+1868",
    flagEmoji: "🇹🇹",
  },
  {
    name: "Tunisia",
    code: "TN",
    phoneCode: "+216",
    flagEmoji: "🇹🇳",
  },
  {
    name: "Turkey",
    code: "TR",
    phoneCode: "+90",
    flagEmoji: "🇹🇷",
  },
  {
    name: "Turkmenistan",
    code: "TM",
    phoneCode: "+993",
    flagEmoji: "🇹🇲",
  },
  {
    name: "Turks and Caicos Islands",
    code: "TC",
    phoneCode: "+1649",
    flagEmoji: "🇹🇨",
  },
  {
    name: "Tuvalu",
    code: "TV",
    phoneCode: "+688",
    flagEmoji: "🇹🇻",
  },
  {
    name: "Uganda",
    code: "UG",
    phoneCode: "+256",
    flagEmoji: "🇺🇬",
  },
  {
    name: "Ukraine",
    code: "UA",
    phoneCode: "+380",
    flagEmoji: "🇺🇦",
  },
  {
    name: "United Arab Emirates",
    code: "AE",
    phoneCode: "+971",
    flagEmoji: "🇦🇪",
  },
  {
    name: "United Kingdom",
    code: "GB",
    phoneCode: "+44",
    flagEmoji: "🇬🇧",
  },
  {
    name: "United States",
    code: "US",
    phoneCode: "+1",
    flagEmoji: "🇺🇸",
  },
  {
    name: "Uruguay",
    code: "UY",
    phoneCode: "+598",
    flagEmoji: "🇺🇾",
  },
  {
    name: "Uzbekistan",
    code: "UZ",
    phoneCode: "+998",
    flagEmoji: "🇺🇿",
  },
  {
    name: "Vanuatu",
    code: "VU",
    phoneCode: "+678",
    flagEmoji: "🇻🇺",
  },
  {
    name: "Venezuela, Bolivarian Republic of Venezuela",
    code: "VE",
    phoneCode: "+58",
    flagEmoji: "🇻🇪",
  },
  {
    name: "Vietnam",
    code: "VN",
    phoneCode: "+84",
    flagEmoji: "🇻🇳",
  },
  {
    name: "Virgin Islands, British",
    code: "VG",
    phoneCode: "+1284",
    flagEmoji: "🇻🇬",
  },
  {
    name: "Virgin Islands, U.S.",
    code: "VI",
    phoneCode: "+1340",
    flagEmoji: "🇻🇮",
  },
  {
    name: "Wallis and Futuna",
    code: "WF",
    phoneCode: "+681",
    flagEmoji: "🇼🇫",
  },
  {
    name: "Yemen",
    code: "YE",
    phoneCode: "+967",
    flagEmoji: "🇾🇪",
  },
  {
    name: "Zambia",
    code: "ZM",
    phoneCode: "+260",
    flagEmoji: "🇿🇲",
  },
  {
    name: "Zimbabwe",
    code: "ZW",
    phoneCode: "+263",
    flagEmoji: "🇿🇼",
  },
];